package advanced

import (
	"net/http"
	"testing"

	"github.com/mkaniukk/netanalytics/pkg/types"
)

func TestCheckWAFHeaders(t *testing.T) {
	tests := []struct {
		name     string
		headers  http.Header
		detected bool
		wafName  string
	}{
		{
			name: "Cloudflare detection",
			headers: http.Header{
				"Cf-Ray": []string{"abc123"},
			},
			detected: true,
			wafName:  "Cloudflare",
		},
		{
			name: "AWS WAF detection",
			headers: http.Header{
				"X-Amzn-Wafblock": []string{"true"},
			},
			detected: true,
			wafName:  "AWS WAF",
		},
		{
			name: "Sucuri via header",
			headers: http.Header{
				"X-Sucuri-Id": []string{"123"},
			},
			detected: true,
			wafName:  "Sucuri",
		},
		{
			name: "No WAF",
			headers: http.Header{
				"Server": []string{"nginx"},
			},
			detected: false,
			wafName:  "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			info := types.WAFInfo{}
			result := checkWAFHeaders(tt.headers, info)

			if result.Detected != tt.detected {
				t.Errorf("Expected detected=%v, got %v", tt.detected, result.Detected)
			}
			if result.Name != tt.wafName {
				t.Errorf("Expected WAF name '%s', got '%s'", tt.wafName, result.Name)
			}
		})
	}
}

func TestCheckWAFBody(t *testing.T) {
	tests := []struct {
		name     string
		body     string
		detected bool
	}{
		{
			name:     "Cloudflare block page",
			body:     "Attention Required! | Cloudflare - Please wait",
			detected: true,
		},
		{
			name:     "Wordfence block page",
			body:     "Generated by Wordfence - blocked request",
			detected: true,
		},
		{
			name:     "Normal page",
			body:     "<html><body>Hello World</body></html>",
			detected: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			info := types.WAFInfo{}
			result := checkWAFBody(tt.body, info)

			if result.Detected != tt.detected {
				t.Errorf("Expected detected=%v, got %v", tt.detected, result.Detected)
			}
		})
	}
}
